### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by stax76** [chikuzen/avs2pipemod#2]
Hi,

I need a ffmpeg alternative for StaxRip because of a bug:

https://trac.ffmpeg.org/ticket/5721#ticket

first I tried avs2yuv and it works fine but development might be dead so I tried avs2pipemod, it crashes, this is my command line:

D:\Temp\Downloads\avs2pipemod-1.0.0\avs2pipemod64.exe -y4mp D:\Temp\Video\Eli_temp\Eli.avs | D:\Projekte\VS\VB\StaxRip\bin\Apps\x265\x265.exe --crf 22 --preset ultrafast --frames 1301 --y4m --output D:\Temp\Video\Eli_temp\Eli.hevc -

I use AviSynth+ x64 r2043

what is the difference between avs2yuv and avs2pipemod?

**Comment by chikuzen** [comment]
I tested as follows

> #test.avs
> ColorBarsHD().Trim(0, 9999)
> 
> .\avs2pipemod64.exe -y4mp .\test.avs | x264_x64.exe - --demuxer y4m --preset ultrafast --crf 22 --log-level warning --frames 1301 -o .\out.mkv
> avs2pipemod[info]: writing 10000 frames of 30000/1001 fps, 1288x720,
>                    sar 0:0, YUV-444-planar-8bit progressive video.
> resize [warning]: converting from yuv444p to yuv420p
> encoded 1301 frames, 404.04 fps, 29.63 kb/s
> avs2pipemod[info]: finished, wrote 1302 frames [13%].
> avs2pipemod[info]: total elapsed time is 3.226 sec.
> avs2pipemod[error]: only wrote 1302 of 10000 frames.  

I coudn't reproduce the crash.

**Comment by stax76** [comment]
it works with ColorBarsHD, with FFVideoSource it says:

avs2pipemod[error]: clip has no audio.

with LSMASHVideoSource it crashes

L-Smash-Works r879 x64
VC++ 2015 Update 3 14.0.24210.0 x64
Win 10 Pro x64

**Comment by chikuzen** [comment]
ok, I found a typo.
try this.
https://dl.dropboxusercontent.com/u/19797864/avs2pipemod-1.0.1.zip

**Comment by stax76** [comment]
this works, thanks!

could -y4mp be made default?

**Comment by chikuzen** [comment]
> could -y4mp be made default?

no.
