### ISSUE TITLE
Formatting mistake in log

### ISSUE THREAD

**Issue by maki-rxrz** [chikuzen/avs2pipemod#3]
avs2pipemod.cpp(216-217)

> ```
> a2pm_log(LOG_INFO, "writing %.3f seconds of %zu Hz, %zu channel audio.\n",
>          1.0 * target / count, count, vi.nchannels);
> ```

avisynth.h の nchannels 定義がint型である為、64bit版は %zu 指定が型サイズ不一致を起こしています。
以下、avs2pipemod64.exeでの出力例です。(2ch音声)

`avs2pipemod[info]: writing 1439.980 seconds of 48000 Hz, 386547056642 channel audio.`

**Comment by chikuzen** [comment]
あらら
なんで俺はsize_tと勘違いしてたのでしょう？
直しときます。
